### ISSUE TITLE
[Crash] Fish Recipe

### ISSUE THREAD

**Issue by FlyNeko48** [Djekke/CNEI#14]
1. Open any fish 
2. Select Recipe tab
3. Switch to another bait
4. Most times game completely closed in a second

Using CNEI v0.4.8, game 0.27.7.20, official server

**Comment by Djekke** [comment]
Looks like I found where this problem, but have no idea why and frankly no idea what exactly going on there and how it should work.
https://github.com/Djekke/CNEI/blob/e806943d8a0982536e45018110db8f5828488a4d/UI/CNEI/Data/EntityTemplates/Recipes/FishingDataTemplate.xaml#L63-L101
Problem with specified `GridViewColumn.Header` in the code above.
The one with `Chance weight` with big and clumsy construction caused crash and the two small one below are just glitchy and behave weirdly (headers disappearing after few seconds after render).
I wanted to blame noesis on that as I found somewhat similar reports on their bugtrecker, so I tried to replicate this on blank noesis project, but so far has no luck on it.
