### ISSUE TITLE
Bug with R31 version

### ISSUE THREAD

**Issue by aienabled** [Djekke/CNEI#17]
Hi,
immediately after the game client starts there are many console errors:
```
Exception thrown from NoesisGUI context
System.Exception: Xaml file not found: UI/Styles/SpecialItemsPanel.xaml
```

Probably this is due to the updated NoesisGUI version that the game uses in R31 version. Not sure if it's actually a game-breaking issue.

Regards!

**Comment by Djekke** [comment]
Thank you for report. it was just a redundant style reference.
Fixed in 430e541506af95d5ac52a0301ef7eede4a8a8e6f
