### ISSUE TITLE
Missing style reference

### ISSUE THREAD

**Issue by jch02140** [Djekke/CNEI#18]
I am still getting a missing style reference error when I log into server of cryofall...

Mod version is latest.

![error](https://user-images.githubusercontent.com/935533/120054843-0ac75e80-c065-11eb-9e93-057d45eece93.jpg)

**Comment by Djekke** [comment]
Please check again if you have latest mod version. (0.4.13)
There is no reference left for `UI/Styles/SpecialItemsPanel.xaml` in this mod files.

**Comment by jch02140** [comment]
Humm.. I downloaded the latest version again and copy it over to my mod folder but the game still says the same error when I join a game. Here is mod config file I have

```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<mods>
  <mod>core_1.0.0</mod>
  <mod>cnei_0.4.13</mod>
  <mod>marketplace_0.1.4</mod>
</mods>
```

**Comment by Djekke** [comment]
Mystery solved, it's `marketplace` mod. Please check again without it and if it confirms create an issue here https://github.com/mars-x24/Marketplace/issues

**Comment by jch02140** [comment]
Hi Djekke, can confirm it is the marketplace plugin that caused the error message. Will post an issue at their github project page now. Thanks.
